version: '{build}'
image: Visual Studio 2017
configuration: Release
platform: Any CPU
before_build:
- cmd: nuget restore src\
build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: SJhz4UnOzI1RS5gzQoav6HbCDis5x7d8QzICFmtX9TuHIOGKXpUtEwwELptoqiZj
  on:
    appveyor_repo_tag: true